#!/usr/bin/env python




#This is the secrete to eternal live 1/2
import os,sys
pwd = os.path.dirname(os.path.realpath(__file__))
sys.path.append(pwd)

##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from templates import genericHeaders
from genericHeaders import genericHeaders

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1342455446.621
__CHEETAH_genTimestamp__ = 'Mon Jul 16 18:17:26 2012'
__CHEETAH_src__ = 'hsmErrors_h.tmpl'
__CHEETAH_srcLastModified__ = 'Mon Jul 16 11:29:26 2012'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class hsmErrors_h(genericHeaders):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(hsmErrors_h, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        # 
        #     This is the template for the hsm errors header
        # 
        #     This is the secret to eternal live 2/2
        #     
        #     Without this you will get no output from the
        #     def's in the parent class
        write(u'''
''')
        #  ############################
        #  Get file header
        #  ############################
        todo = 'TODO'
        name = VFSL([locals()]+SL+[globals(), builtin],"srv.Name",True) + '.Errors'
        _v = VFSL([locals()]+SL+[globals(), builtin],"InsertFileHeader",False)(VFSL([locals()]+SL+[globals(), builtin],"name",True), VFSL([locals()]+SL+[globals(), builtin],"extension",True), VFSL([locals()]+SL+[globals(), builtin],"todo",True)) # u'$InsertFileHeader($name, $extension, $todo)' on line 19, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$InsertFileHeader($name, $extension, $todo)')) # from line 19, col 1.
        write(u'''

// 
//    This file is included inside enumeration definition, and to create an error name table
//    inside class definition in the .h of your class
//    #include enumdefs.h
//    enum
//    {
//        #include "''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 27, col 22
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 27, col 22.
        _v = VFSL([locals()]+SL+[globals(), builtin],"extension",True) # u'${extension}' on line 27, col 29
        if _v is not None: write(_filter(_v, rawExpr=u'${extension}')) # from line 27, col 29.
        write(u'''"
//    };
// 
//   and in the .cc create a table errors and their enums
// 
//   #include enumstrdefs.h - MUST BE AFTER INCLUDE OF CLASS HEADER
//   const static ENUM_STRING Errors[] = 
//   {
//      #include "''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"name",True) # u'${name}' on line 35, col 20
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 35, col 20.
        _v = VFSL([locals()]+SL+[globals(), builtin],"extension",True) # u'${extension}' on line 35, col 27
        if _v is not None: write(_filter(_v, rawExpr=u'${extension}')) # from line 35, col 27.
        write(u'''"
//   };

ENUM_SET(UNEXPECTED_ERROR,ERROR_BASE_DEVICE)    // 400 - occurs when .. TODO
ENUMTERM
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_hsmErrors_h= u'respond'

## END CLASS DEFINITION

if not hasattr(hsmErrors_h, '_initCheetahAttributes'):
    templateAPIClass = getattr(hsmErrors_h, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(hsmErrors_h)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=hsmErrors_h()).run()


